# Generated by Django 3.2.3 on 2021-08-10 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variation_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
            ],
        ),
    ]
